config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # FHIR Bulk Export routes
  get 'export', to: 'export#index', as: 'export'
  post 'export/start', to: 'export#start', as: 'start_export'
  get 'export/status', to: 'export#status', as: 'export_status'
  delete 'export/cancel', to: 'export#cancel', as: 'cancel_export'
  get 'pharmacymix/index'
  get 'controllername/pharmacymix'
  get 'controllername/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  resources :healthcare_services, only: [:index, :show] do
    get 'search', on: :collection
  end

  resources :pharmacies, only: [:index] do
    get 'search', on: :collection
  end

  resources :pharmacymixes, only: [:index] do
    get 'search', on: :collection
  end

  get '/providers/networks', to: 'providers#networks'
  get '/providers/search', to: 'providers#search'

  resources :endpoints,                 only: [:index, :show]
  resources :insurance_plans,           only: [:index, :show]
  resources :locations,                 only: [:index, :show]
  resources :networks,                  only: [:index, :show]
  resources :organizations,             only: [:index, :show]
  resources :organization_affiliations, only: [:index, :show]
  resources :practitioners,             only: [:index, :show]
  resources :practitioner_roles,        only: [:index, :show]
  resources :providers,                 only: [:index]
  resources :pharmacies,                only: [:index]
  resources :pharmacymixes,             only: [:index]
end

app/models/practitioner.rb
# frozen_string_literal: true

################################################################################
#
# Practitioner Model
#
# Copyright (c) 2019 The MITRE Corporation.  All rights reserved.
#
################################################################################

class Practitioner < Resource
  include ActiveModel::Model

  attr_accessor :id, :meta, :implicit_rules, :language, :text, :identifier,
                :active, :new_patient, :name, :telecoms, :addresses, :gender, :birthDate,
                :photo, :qualifications, :communications, :extensions

  #-----------------------------------------------------------------------------

  def initialize(practitioner)
    @id = practitioner.id
    @name = practitioner.name
    @telecoms = practitioner.telecom
    @addresses = practitioner.address
    @gender = practitioner.gender
    @birthDate = practitioner.birthDate
    @photo = practitioner.photo
    @qualifications = practitioner.qualification
    @communications = practitioner.communication
    @extensions = practitioner.extension
    
    if gender.eql?("female")
        @photo = "female-doctor-icon-9.jpg"
        @phototitle = "Female Doctor Icon #279694"
    else
         @photo = "doctor-icon-png-1.jpg"
         @phototitle = "Doctor Icon Png #418309"
    end
  end

  #-----------------------------------------------------------------------------

  def self.query_params
    [
      {
        name: 'Endpoint',
        value: 'endpoint'
      },
      {
        name: 'Family name',
        value: 'family:contains'
      },
      {
        name: 'Given name',
        value: 'given:contains'
      },
      {
        name: 'Identfier Assigner',
        value: 'identifier-assigner'
      },
      {
        name: 'Identifier',
        value: 'identifier'
      },
      {
        name: 'Name',
        value: 'name:contains'
      },
      {
        name: 'Phonetic',
        value: 'phonetic'
      },
      {
        name: 'Qualification Code',
        value: 'practitioner-qualification-code'
      },
      {
        name: 'Qualification Issuer',
        value: 'practitioner-qualification-issuer'
      },
      {
        name: 'ID',
        value: '_id'
      },
      {
        name: 'Last Updated',
        value: '_lastUpdated'
      },
      #{
      #  name: 'Qualification Period',
      #  value: 'qualification-period'
      #},
      #{
      #  name: 'Qualification Status',
      #  value: 'qualification-status'
      #},
      #{
      #  name: 'Qualification Where Valid Code',
      #  value: 'qualification-wherevalid-code'
      #},
      #{
      #  name: 'Qualification Where Valid Location',
      #  value: 'qualification-wherevalid-location'
      #}
    ]
  end

end

app/controllers/practitioners_controller.rb
# frozen_string_literal: true

################################################################################
#
# Practitioners Controller
#
# Copyright (c) 2019 The MITRE Corporation.  All rights reserved.
#
################################################################################

require 'json'
require 'cgi'

class PractitionersController < ApplicationController

  before_action :connect_to_server, only: [:index, :show]

  # FHIR.logger.level = Logger::WARN
  #-----------------------------------------------------------------------------

  # GET /practitioners

  def index
    return unless @client

    if params[:page].present?
      update_page(params[:page])
    else
      if params[:query_string].present?
        parameters = query_hash_from_string(params[:query_string])
        reply = @client.search(
          FHIR::Practitioner,
          search: {
            parameters: parameters.merge(
    #          _profile: 'http://hl7.org/fhir/us/davinci-pdex-plan-net/StructureDefinition/plannet-Practitioner'
            )
          }
        )
      else
        reply = @client.search(
          FHIR::Practitioner,
          search: {
            parameters: {
     #         _profile: 'http://hl7.org/fhir/us/davinci-pdex-plan-net/StructureDefinition/plannet-Practitioner'
            }
          }
        )
      end

      @bundle = reply.resource
      @search = "<Search String in Returned Bundle is empty>"
      @search = CGI.unescape(@bundle.link.select { |l| l.relation === "self"}.first.url) if @bundle.link.first 
    end

    update_bundle_links

    @query_params = Practitioner.query_params
    @practitioners = @bundle.present? ? @bundle.entry.map(&:resource) : []
    @params = params
  end

  #-----------------------------------------------------------------------------

  # GET /practitioners/[id]

  def show
    return unless @client

    reply = @client.read(FHIR::Practitioner, params[:id])
    fhir_practitioner = reply.resource
    @practitioner = Practitioner.new(fhir_practitioner) unless fhir_practitioner.nil?
  end

end

app/helpers/practitioner_helper.rb
# frozen_string_literal: true

################################################################################
#
# Practitioner Helper
#
# Copyright (c) 2019 The MITRE Corporation.  All rights reserved.
#
################################################################################

module PractitionerHelper

  def display_qualification(qualification)
    sanitize(qualification.identifier)
  end

  #-----------------------------------------------------------------------------

  def display_code(code)
    sanitize(code.coding.display)
  end

  #-----------------------------------------------------------------------------

  def display_period(period, include_label: true)
    return '' unless period.present?

    start_date = format_period_date(period.start)
    end_date = format_period_date(period.end)

    result = if start_date.present? && end_date.present?
               "#{start_date} to #{end_date}"
             elsif start_date.present?
               "#{start_date} onwards"
             elsif end_date.present?
               "until #{end_date}"
             else
               ''
             end

    return '' if result.blank?

    result = "Effective #{result}" if include_label
    sanitize(result)
  end

  def format_period_date(date_string)
    return nil if date_string.blank?

    # Parse ISO 8601 date and format as YYYY-MM-DD
    Date.parse(date_string).strftime('%Y-%m-%d')
  rescue ArgumentError
    date_string
  end

  #-----------------------------------------------------------------------------

  def display_issuer(issuer)
    sanitize(issuer.display)
  end

  #-----------------------------------------------------------------------------

  def display_photo(photo, gender, options)
      options [:class] = "img-fluid"
      image_tag(photo, options)
  end
  
end

app/views/practitioners/_qualification.html.erb
<% qualification.identifier.each do |identifier| %>
  <%= display_identifier(identifier) %>
  (<%= display_period(identifier.period) %>)<br />
<% end %>
<% qualification.code.coding.each do |coding| %>
  <%= sanitize(coding.display) %><br />
  <br />
<% end %>

app/views/practitioners/index.html.erb
<section class='container'>
  <h3 class='page-title'>
    Practitioners
    <%= ("named '" + sanitize(@params[:name]) + "'") unless @params.nil? || @params[:name].nil? %>
  </h3>

  <% if @client %>
  <section class='row'>
    <div class='col-12'>
      <%= render 'partials/query' %>
      <%= render 'partials/pagination', resource: :practitioners %>
    </div>
    <div class='col-12'>
      <div class="accordion mb-4" id="searchAccordion">
        <div class="accordion-item">
          <h2 class="accordion-header" id="headingOne">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
              Search
            </button>
          </h2>
          <div id="collapseOne" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#searchAccordion">
            <div class="accordion-body">
              <%= render 'partials/search_form',
                         query_params: @query_params,
                         search_path: practitioners_path
              %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class='col-12'>
      <table class='table table-dark table-striped'>
        <thead>
          <tr>
            <th scope='col'>Name</th>
            <th scope='col'>Phone/Fax</th>
            <th scope='col'>Locations</th>
            <th scope='col'>Gender</th>
            <th scope='col'>Licenses</th>
          </tr>
        </thead>
        <tbody>
          <% @practitioners.each do |fhir_practitioner| %>
            <% practitioner = Practitioner.new(fhir_practitioner) %>
            <tr>
              <td>
                <%= link_to practitioner_path(practitioner.id) do %>
                  <%= display_photo(practitioner.photo, practitioner.gender, 
                            class: 'list-photo') %><br />
                  <%= display_human_name(practitioner.name.first) %>
                <% end %>
              </td>
              <td>
                <% practitioner.telecoms.each do |telecom| %>
                  <%= display_telecom(telecom) %><br /><br />
                <% end %>
              </td>
              <td>
                <% practitioner.addresses.each do |address| %>
                  <%= render partial: 'partials/address', 
                              locals: { address: address } %>
                <% end %>
              </td>
              <td><%= practitioner.gender %></td>
              <td>
                <% practitioner.qualifications.each do |qualification| %>
                  <%= render partial: 'qualification', 
                            locals: { qualification: qualification } %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class='col-12'>
      <%= render 'partials/pagination', resource: :practitioners, header: false %>
    </div>
  </section>
  <% else %>
    <%= render 'partials/server_connect' %>
  <% end %>
</section>

app/views/practitioners/show.html.erb
<section class='container'>
  <% if @client %>
  <section class='row'>
    <% unless @practitioner.nil? %>
      <div class='col-12'>
        <h2><%= display_human_name(@practitioner.name.first) %></h2>
      </div>
      <div class='col-6'>
        <%= display_photo(@practitioner.photo, @practitioner.gender, 
                    class: 'profile-photo') %>
      </div>
      <div class='col-6'>
        <table class='table table-dark'>
          <tr>
            <td>Phone/Fax:</td>
            <td>
              <% @practitioner.telecoms.each do |telecom| %>
                <%= display_telecom(telecom) %><br />
              <% end %>
            </td>
          </tr>
          <tr>
            <td>Locations:</td>
            <td>
              <% @practitioner.addresses.each do |address| %>
                <%= render partial: 'partials/address', 
                            locals: { address: address } %>
              <% end %>
            </td>
          </tr>
          <tr>
            <td>Gender:</td>
            <td><%= @practitioner.gender %></td>
          </tr>
          <tr>
            <td>Licenses:</td>
            <td>           
              <% @practitioner.qualifications.each do |qualification| %>
                <%= render partial: 'qualification', 
                          locals: { qualification: qualification } %>
                Period: <%= display_period(qualification.period) %><br />
                Issuer: <%= display_issuer(qualification.issuer) %><br />
                <br />
              <% end %>
            </td>
          </tr>
          <% @practitioner.extensions.each do |extension| %>
          <tr>
            <td><%= extension_title(extension.url) %>:</td>
            <td>
              <% if extension.extension.present? %>
              <!-- only going one level deep on extensions -->
                <% extension.extension.each do |child_extension| %>
                  <%= extension_title(child_extension.url) %>: <i><%= display_leaf_extension(child_extension) %></i>
                  <br />
                <% end %>
              <% else %>
                <%= display_leaf_extension(extension) %>
              <% end %>
              <br />
            </td>
          <tr>
        <% end %>
        </table>
      </div>
    <% else %>
      Not Found
    <% end %>
  </section>
  <% else %>
    <%= render 'partials/server_connect' %>
  <% end %>
</section>