config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # FHIR Bulk Export routes
  get 'export', to: 'export#index', as: 'export'
  post 'export/start', to: 'export#start', as: 'start_export'
  get 'export/status', to: 'export#status', as: 'export_status'
  delete 'export/cancel', to: 'export#cancel', as: 'cancel_export'
  get 'pharmacymix/index'
  get 'controllername/pharmacymix'
  get 'controllername/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  resources :healthcare_services, only: [:index, :show] do
    get 'search', on: :collection
  end

  resources :pharmacies, only: [:index] do
    get 'search', on: :collection
  end

  resources :pharmacymixes, only: [:index] do
    get 'search', on: :collection
  end

  get '/providers/networks', to: 'providers#networks'
  get '/providers/search', to: 'providers#search'

  resources :endpoints,                 only: [:index, :show]
  resources :insurance_plans,           only: [:index, :show]
  resources :locations,                 only: [:index, :show]
  resources :networks,                  only: [:index, :show]
  resources :organizations,             only: [:index, :show]
  resources :organization_affiliations, only: [:index, :show]
  resources :practitioners,             only: [:index, :show]
  resources :practitioner_roles,        only: [:index, :show]
  resources :providers,                 only: [:index]
  resources :pharmacies,                only: [:index]
  resources :pharmacymixes,             only: [:index]
end

app/views/partials/_address.html.erb
<% if address.present? %>
  <%= link_to google_maps(address), target: '_blank' do %>
    <% address.line.each do |line| %>
      <%= sanitize(line) %><br />
    <% end %>
    <%= sanitize(address.city) %>, 
    <%= sanitize(address.state) %> 
    <%= display_postal_code(address.postalCode) %>
  <% end %><br />
  <br />
<% end %>

app/views/partials/_footer.html.erb
<!-- MDB Material Design Footer (Dark Theme) -->
<footer class="py-3 mt-auto">
	<div class="container-fluid">
		<div class="row align-items-center">
			<div class="col-md-8">
				<p class="mb-1 small">
					Zipcode data provided by 
					<a href="https://public.opendatasoft.com/explore/dataset/us-zip-code-latitude-and-longitude/table/" class="text-decoration-none">Opendatasoft</a>.
				</p>
			</div>
		</div>
	</div>
</footer>

app/views/partials/_head.html.erb
<head>
	<title>National Directory</title>
	<%= csrf_meta_tags %>
	<%= csp_meta_tag %>

	<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
	
	<!-- Map Libraries -->
	<link rel="stylesheet" href="https://cdn.rawgit.com/openlayers/openlayers.github.io/master/en/v5.3.0/css/ol.css" type="text/css">
	<script src="https://cdn.rawgit.com/openlayers/openlayers.github.io/master/en/v5.3.0/build/ol.js"></script>
	<link rel="stylesheet" href="https://unpkg.com/leaflet@1.5.1/dist/leaflet.css" integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ==" crossorigin=""/>
	<script src="https://unpkg.com/leaflet@1.5.1/dist/leaflet.js" integrity="sha512-GffPMF3RvMeYyc1LWMHtK8EbPv0iNZ8/oTtHPx9/cc2ILxQ+u905qIwdpULaqDkyBKgOaB57QTMg7ztg8Jm2Og==" crossorigin=""></script>
	
	<script>
		$(document).ready(function(){
			// Initialize Bootstrap 5 tooltips
			var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'));
			tooltipTriggerList.map(function (el) {
				return new bootstrap.Tooltip(el);
			});
		});
	</script>
	
	<%= favicon_link_tag asset_path('ndh-query-client.ico') %>
</head>

app/views/partials/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
	<div class="container-fluid">
		<%= link_to root_path, class: 'navbar-brand' do %>
			<%= image_tag 'telephone-directory.svg', id: 'logo', width: 30, height: 30, alt: '' %>
			National Directory
		<% end %>
		<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarNav">
			<ul class="navbar-nav">
				<li class="nav-item">
					<%= link_to 'Services', healthcare_services_path, class: 'nav-link' %>
				</li>
				<li class="nav-item">
					<%= link_to 'Providers', providers_path, class: 'nav-link' %>
				</li>
				<li class="nav-item">
					<%= link_to 'Pharmacies', pharmacies_path, class: 'nav-link' %>
				</li>
				<li class="nav-item">
					<%= link_to 'Export', export_path, class: 'nav-link' %>
				</li>
				<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown">Resources</a>
					<ul class="dropdown-menu dropdown-menu-dark">
						<li><%= link_to 'Endpoints', endpoints_path, class: 'dropdown-item' %></li>
						<li><%= link_to 'Insurance Plans', insurance_plans_path, class: 'dropdown-item' %></li>
						<li><%= link_to 'Locations', locations_path, class: 'dropdown-item' %></li>
						<li><%= link_to 'Networks', networks_path, class: 'dropdown-item' %></li>
						<li><%= link_to 'Organizations', organizations_path, class: 'dropdown-item' %></li>
						<li><%= link_to 'Organization Affiliation', organization_affiliations_path, class: 'dropdown-item' %></li>
						<li><%= link_to 'Practitioners', practitioners_path, class: 'dropdown-item' %></li>
						<li><%= link_to 'Practitioner Roles', practitioner_roles_path, class: 'dropdown-item' %></li>
					</ul>
				</li>
			</ul>
			<ul class="navbar-nav ms-auto">
				<li class="nav-item">
					<% if cookies[:server_url].present? %>
						<span class="navbar-text text-success">
							<strong>Connected:</strong> <%= cookies[:server_url] %>
						</span>
					<% else %>
						<span class="navbar-text text-warning">
							<strong>Not Connected to FHIR Server</strong>
						</span>
					<% end %>
				</li>
			</ul>
		</div>
	</div>
</nav>

app/views/partials/_map.html.erb
<script type="text/javascript">
var baseMapLayer = new ol.layer.Tile({
 source: new ol.source.OSM()
});
var map = new ol.Map({
  target: 'map',
  layers: [ baseMapLayer],
  view: new ol.View({
	center: ol.proj.fromLonLat([ <%= long %>,  <%= lat %> ]), 
	zoom: 15 
  })
});
var marker = new ol.Feature({
  geometry: new ol.geom.Point(
   ol.proj.fromLonLat( [<%= long %>,  <%= lat %> ])
  )
});
var vectorSource = new ol.source.Vector({
features: [marker]
});
var markerVectorLayer = new ol.layer.Vector({
source: vectorSource,
});
map.addLayer(markerVectorLayer);
</script>

app/views/partials/_mapleaflet.html.erb
<script type="text/javascript">
      var mymap = L.map('map').setView([<%= lat %> , <%= long %>], 13);
        L.tileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
            attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, <a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
            maxZoom: 18
         }).addTo(mymap);
        var marker = L.marker([<%= lat %> , <%= long %>]).addTo(mymap);
</script>

app/views/partials/_messages.html.erb
<% if flash.count > 0 %>
	<section class='container messages'>
		<section class='row col-12'>
			<% flash.each do |key, value| %>
				<% if key.is_a?(String) %>
				  <div data-alert class="<%= flash_class(key) %> alert dismissible fade show col-12" role="alert">
				    <%= value %>
						<button type='button' class='close' data-dismiss='alert' aria-label='Close'>
							<span aria-hidden='true'>&times;</span>
						</button>
				  </div>
				<% end %>
			<% end %>
		</section>
	</section>
<% end %>

app/views/partials/_pagination.html.erb
<div class='btn-group float-right mt-2' role='group'>
  <%= link_to('Previous',
    polymorphic_path(resource, page: 'previous'),
    class: "btn btn-outline-primary #{@previous_page_disabled}")
  %>
  <%= link_to('Next',
    polymorphic_path(resource, page: 'next'),
    class: "btn btn-outline-primary #{@next_page_disabled}")
  %>
</div>

app/views/partials/_pagination_remote.html.erb
<div class='btn-group float-right mt-2' role='group'>
  <%= link_to('Previous',
    polymorphic_path(resource, action: 'search', page: 'previous'), remote: true,
    class: "btn btn-outline-primary #{@previous_page_disabled}")
  %>
  <%= link_to('Next',
    polymorphic_path(resource, action: 'search', page: 'next'), remote: true,
    class: "btn btn-outline-primary #{@next_page_disabled}")
  %>
</div>

app/views/partials/_query.html.erb
<% if @search %>
  <div class="row col-12 query">
    <p style="float:left;">Query to server: </p>
    <p style="float:left;"><%= @search %></p>
  </div>
<% end %>

app/views/partials/_search_form.html.erb
<div id="search-params">
  <div class="input-group mb-3">
    <select class="form-select" onchange="updateQueryString(event)">
      <% if query_params.present? %>
        <% query_params.each do |param| %>
          <option value="<%= param[:value] %>"><%= param[:name] %></option>
        <% end %>
      <% end %>
    </select>
    <input type="text" class="form-control" onkeyup="updateQueryString(event)">
    <button class="btn btn-outline-secondary" type="button" onclick="addSearchField(event)">+</button>
  </div>
</div>
<div id="search-url"></div>
<%= form_tag search_path, method: 'get' do %>
  <div class='row'></div>
  <%= hidden_field_tag(:query_string) %>
  <%= button_tag id: 'search-button', class: 'btn btn-outline-success' do %>
    Find
  <% end %>
<% end %>

app/views/partials/_server_connect.html.erb
<div class="row justify-content-center">
	<div class="col-md-8 col-lg-6">
		<div class="card">
			<div class="card-header bg-primary text-white">
				<h5 class="mb-0">Connect to FHIR Server</h5>
			</div>
			<div class="card-body">
				<p class="text-muted mb-3">Please connect to a FHIR server to continue.</p>
				<%= form_tag root_path, method: 'get', class: 'd-flex gap-2', id: 'server-form' do %>
					<div class='flex-grow-1'>
						<%= text_field_tag :server_url, (cookies[:server_url] || 'https://ndh-server.fast.hl7.org/fhir'), class: 'form-control', placeholder: 'Enter FHIR server URL' %>
					</div>
					<%= button_tag class: 'btn btn-primary', id: 'server-url' do %>
						Connect
					<% end %>
				<% end %>
			</div>
		</div>
	</div>
</div>