config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # FHIR Bulk Export routes
  get 'export', to: 'export#index', as: 'export'
  post 'export/start', to: 'export#start', as: 'start_export'
  get 'export/status', to: 'export#status', as: 'export_status'
  delete 'export/cancel', to: 'export#cancel', as: 'cancel_export'
  get 'pharmacymix/index'
  get 'controllername/pharmacymix'
  get 'controllername/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  resources :healthcare_services, only: [:index, :show] do
    get 'search', on: :collection
  end

  resources :pharmacies, only: [:index] do
    get 'search', on: :collection
  end

  resources :pharmacymixes, only: [:index] do
    get 'search', on: :collection
  end

  get '/providers/networks', to: 'providers#networks'
  get '/providers/search', to: 'providers#search'

  resources :endpoints,                 only: [:index, :show]
  resources :insurance_plans,           only: [:index, :show]
  resources :locations,                 only: [:index, :show]
  resources :networks,                  only: [:index, :show]
  resources :organizations,             only: [:index, :show]
  resources :organization_affiliations, only: [:index, :show]
  resources :practitioners,             only: [:index, :show]
  resources :practitioner_roles,        only: [:index, :show]
  resources :providers,                 only: [:index]
  resources :pharmacies,                only: [:index]
  resources :pharmacymixes,             only: [:index]
end

app/models/endpoint.rb
# frozen_string_literal: true

################################################################################
#
# Endpoint Model
#
# Copyright (c) 2019 The MITRE Corporation.  All rights reserved.
#
################################################################################

class Endpoint < Resource
  include ActiveModel::Model

  attr_accessor :id, :meta, :implicit_rules, :language, :text, :identifier,
                :active, :connection_type, :name, :managing_organization,
                :contacts, :period, :payload_types, :payload_mime_types,
                :headers, :extensions

  #-----------------------------------------------------------------------------

  def initialize(endpoint)
    @id = endpoint.id
    @connection_type = endpoint.connectionType
    @name = endpoint.name
    @managing_organization = endpoint.managingOrganization
    @contacts = endpoint.contact
    @period = endpoint.period
    @payload_types = endpoint.payloadType
    @payload_mime_types = endpoint.payloadMimeType
    @headers = endpoint.header
    @extensions = endpoint.extension
  end

  #-----------------------------------------------------------------------------

  # FHIR search query parameters for Endpoints are:
  #
  #   _id, _language, connection-type, identifier, identifier-assigner, mime-type,
  #   name, organization, payload-type, status, usecase-standard, usecase-type,
  #   via-intermediary

  def self.search(server, query)
    parameters = {}

    query.each do |key, value|
      parameters[key] = value unless value.empty?
    end

    server.search(FHIR::Endpoint, search: { parameters: parameters })
  end

  #-----------------------------------------------------------------------------

  def self.query_params
    [
      {
        name: 'Connection Type',
        value: 'connection-type'
      },
      {
        name: 'ID',
        value: '_id'
      },
      {
        name: 'Last Updated',
        value: '_lastUpdated'
      },
      {
        name: 'Identifier',
        value: 'identifier'
      },
      #{
      #  name: 'Identifier Assigner',
      #  value: 'identifier-assigner'
      #},
     # {
     #   name: 'Intermediary',
     #   value: 'via-intermediary'
     # },
      #{
      #  name: 'MIME Type',
      #  value: 'mime-type'
      #},

      {
        name: 'Use Case Type',
        value: 'endpoint-usecase-type'
      },
      {
        name: 'Non-FHIR Use Case Type',
        value: 'endpoint-nonfhir-usecase-type'
      },
      {
        name: 'Trust Framework Type',
        value: 'endpoint-trust-framework-type'
      },
      {
        name: 'Dynamic Registration Trust Profile',
        value: 'endpoint-dynamic-registration-trust-profile'
      },
      {
        name: 'Access Control Mechanism',
        value: 'endpoint-access-control-mechanism'
      },
      {
        name: 'Connection Type Version',
        value: 'endpoint-connection-type-version'
      },
      {
        name: 'IHE Connection Type',
        value: 'endpoint-ihe-connection-type'
      },
      {
        name: 'Verification Status',
        value: 'endpoint-verification-status'
      },
      {
        name: 'Organization',
        value: 'organization'
      },
      {
        name: 'Payload Type',
        value: 'payload-type'
      },
      {
        name: 'Status',
        value: 'status'
      },
      {
        name: 'Use Case Standard',
        value: 'endpoint-usecase-standard'
      }
    ]
  end

end

app/controllers/endpoints_controller.rb
# frozen_string_literal: true

################################################################################
#
# Endpoints Controller
#
# Copyright (c) 2019 The MITRE Corporation.  All rights reserved.
#
################################################################################

require 'json'
require 'cgi'

class EndpointsController < ApplicationController
  before_action :connect_to_server, only: [:index, :show]

  #-----------------------------------------------------------------------------

  # GET /endpoints

  def index
    return unless @client

    if params[:page].present?
      update_page(params[:page])
    else
      if params[:query_string].present?
        parameters = query_hash_from_string(params[:query_string])
        reply = @client.search(
          FHIR::Endpoint,
          search: {
            parameters: parameters.merge(
        #      _profile: 'http://hl7.org/fhir/us/davinci-pdex-plan-net/StructureDefinition/plannet-Endpoint'
            )
          }
        )         
      else
        reply = @client.search(
          FHIR::Endpoint,
          search: {
            parameters: {
        #      _profile: 'http://hl7.org/fhir/us/davinci-pdex-plan-net/StructureDefinition/plannet-Endpoint'
            }
          }
        )
      end

      @bundle = reply.resource
      @search = "<Search String in Returned Bundle is empty>"
      @search = CGI.unescape(@bundle.link.select { |l| l.relation === "self"}.first.url) if @bundle.link.first 
    end

    update_bundle_links

    @query_params = Endpoint.query_params
    @endpoints = @bundle.entry.map(&:resource)
  end

  #-----------------------------------------------------------------------------

  # GET /endpoints/[id]

  def show
    return unless @client

    reply = @client.read(FHIR::Endpoint, params[:id])
    fhir_endpoint = reply.resource
    @endpoint = Endpoint.new(fhir_endpoint) unless fhir_endpoint.nil?
  end

end

app/views/endpoints/index.html.erb
<section class='container'>
  <h3 class='page-title'>Endpoints</h3>

  <% if @client %>
  <section class='row'>
    <div class='col-12'>
      <%= render 'partials/query' %>
      <%= render 'partials/pagination', resource: :endpoints %>
    </div>
    <div class='col-12'>
      <div class="accordion mb-4" id="searchAccordion">
        <div class="accordion-item">
          <h2 class="accordion-header" id="headingOne">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
              Search
            </button>
          </h2>
          <div id="collapseOne" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#searchAccordion">
            <div class="accordion-body">
              <%= render 'partials/search_form',
                         query_params: @query_params,
                         search_path: endpoints_path
              %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class='col-12 table-responsive'>
      <table class='table table-dark table-striped'>
        <thead>
          <tr>
            <th scope='col'>Name</th>
            <th scope='col'>Connection Type</th>
            <th scope='col'>Managing Organization</th>
            <th scope='col'>Contacts</th>
            <th scope='col'>Period</th>
            <th scope='col'>Payload Types</th>
            <th scope='col'>Payload MIME Types</th>
            <th scope='col'>Headers</th>
          </tr>
        </thead>
        <tbody>
          <% @endpoints.each do |fhir_endpoint| %>
            <% endpoint = Endpoint.new(fhir_endpoint) %>
            <tr>
              <td><%= link_to sanitize(endpoint.name), endpoint_path(endpoint.id) %></td>
              <td><%= sanitize(endpoint.connection_type.display) %></td>
              <td><%= display_reference(endpoint.managing_organization) %></td>
              <td>
                <% endpoint.contacts.each do |contact| %>
                  <%= display_telecom(contact) %><br />
                <% end %>
              </td>
              <td><%= sanitize(endpoint.period) %></td>
              <td><%= display_coding_list(endpoint.payload_types) %></td>
              <td><%= sanitize(endpoint.payload_mime_types.join(', ')) %></td>
              <td><%= display_list(endpoint.headers) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class='col-12'>
      <%= render 'partials/pagination', resource: :endpoints, header: false %>
    </div>
  </section>
  <% else %>
    <%= render 'partials/server_connect' %>
  <% end %>
</section>

app/views/endpoints/show.html.erb
<section class='container'>
  <% if @client %>
  <section class='row col-12'>
    <% unless @endpoint.nil? %>
      <h2><%= sanitize(@endpoint.name) %></h2>
      <table class='table table-dark'>
        <tr>
          <td>Connection Type:</td>
          <td><%= display_coding(@endpoint.connection_type) %></td>
        </tr>
        <tr>
          <td>Managing Organization:</td>
          <td><%= display_reference(@endpoint.managing_organization) %></td>
        </tr>
        <tr>
          <td>Phone/Fax:</td>
          <td>
            <% @endpoint.contacts.each do |contact| %>
              <%= display_telecom(contact) %><br />
            <% end %>
          </td>
        </tr>
        <tr>
          <td>Period:</td>
          <td><%= sanitize(@endpoint.period) %></td>
        </tr>
        <tr>
          <td>Payload Types:</td>
          <td><%= display_coding_list(@endpoint.payload_types) %></td>
        </tr>
        <tr>
          <td>Payload MIME Types:</td>
          <td><%= sanitize(@endpoint.payload_mime_types.join(', ')) %></td>
        </tr>
        <tr>
          <td>Headers</td>
          <td><%= display_list(@endpoint.headers) %></td>
        </tr>
        <% @endpoint.extensions.each do |extension| %>
          <tr>
            <td><%= extension_title(extension.url) %>:</td>
            <td>
              <% if extension.extension.present? %>
              <!-- only going one level deep on extensions -->
                <% extension.extension.each do |child_extension| %>
                  <%= extension_title(child_extension.url) %>: <i><%= display_leaf_extension(child_extension) %></i>
                  <br />
                <% end %>
              <% else %>
                <%= display_leaf_extension(extension) %>
              <% end %>
              <br />
            </td>
          <tr>
        <% end %>
      </table>
    <% else %>
      Not available
    <% end %>
  </section>
  <% else %>
    <%= render 'partials/server_connect' %>
  <% end %>
</section>