config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # FHIR Bulk Export routes
  get 'export', to: 'export#index', as: 'export'
  post 'export/start', to: 'export#start', as: 'start_export'
  get 'export/status', to: 'export#status', as: 'export_status'
  delete 'export/cancel', to: 'export#cancel', as: 'cancel_export'
  get 'pharmacymix/index'
  get 'controllername/pharmacymix'
  get 'controllername/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  resources :healthcare_services, only: [:index, :show] do
    get 'search', on: :collection
  end

  resources :pharmacies, only: [:index] do
    get 'search', on: :collection
  end

  resources :pharmacymixes, only: [:index] do
    get 'search', on: :collection
  end

  get '/providers/networks', to: 'providers#networks'
  get '/providers/search', to: 'providers#search'

  resources :endpoints,                 only: [:index, :show]
  resources :insurance_plans,           only: [:index, :show]
  resources :locations,                 only: [:index, :show]
  resources :networks,                  only: [:index, :show]
  resources :organizations,             only: [:index, :show]
  resources :organization_affiliations, only: [:index, :show]
  resources :practitioners,             only: [:index, :show]
  resources :practitioner_roles,        only: [:index, :show]
  resources :providers,                 only: [:index]
  resources :pharmacies,                only: [:index]
  resources :pharmacymixes,             only: [:index]
end

app/models/organization.rb
# frozen_string_literal: true

################################################################################
#
# Organization Model
#
# Copyright (c) 2019 The MITRE Corporation.  All rights reserved.
#
################################################################################

class Organization < Resource
  
  include ActiveModel::Model

  attr_accessor :id, :meta, :implicit_rules, :language, :text, :identifier,
                :active, :name, :telecoms, :addresses, :contacts, :geolocation, :type, :extensions

  #-----------------------------------------------------------------------------

  def initialize(organization)
    @id = organization.id
    @name = organization.name
    @telecoms = organization.telecom
    @addresses = organization.address
    @contacts = organization.contact
    @type = organization.type 
    @extensions = organization.extension 
    parse_address(organization)

  end

  #-----------------------------------------------------------------------------

  def self.query_params
    [
      {
        name: 'Active',
        value: 'active'
      },
      {
        name: 'Address',
        value: 'address'
      },
      {
        name: 'City',
        value: 'address-city'
      },
      {
        name: 'Country',
        value: 'address-country'
      },
      #{
      #  name: 'Coverage Area',
      #  value: 'coverage-area'
      #},
      {
        name: 'Endpoint',
        value: 'endpoint'
      },
      {
        name: 'ID',
        value: '_id'
      },
      {
        name: 'Last Updated',
        value: '_lastUpdated'
      },
      {
        name: 'Identifier',
        value: 'identifier'
      },
      {
        name: 'Identifier Assigner',
        value: 'identifier-assigner'
      },
      {
        name: 'Intermediary',
        value: 'via-intermediary'
      },
      {
        name: 'Name',
        value: 'name:contains'
      },
      {
        name: 'Part of',
        value: 'partof'
      },
      {
        name: 'Postal Code',
        value: 'address-postalcode'
      },
      #{
      #  name: 'Qualification Code',
      #  value: 'qualification-code'
      #},
      #{
      #  name: 'Qualification Issuer',
      #  value: 'qualification-issuer'
      #},
      #{
      #  name: 'Qualification Status',
      #  value: 'qualification-status'
      #},
      #{
      #  name: 'Qualification Where Valid Code',
      #  value: 'qualification-wherevalid-code'
      #},
      #{
      #  name: 'Qualification Where Valid Location',
      #  value: 'qualification-wherevalid-location'
      #},
      {
        name: 'State',
        value: 'address-state'
      },
      #{
      #  name: 'Telecom Available Days',
      #  value: 'telecom-available-days'
      #},
      #{
      #  name: 'Telecom Available End Time',
      #  value: 'telecom-available-endtime'
      #},
      #{
      #  name: 'Telecom Available Start Time',
      # value: 'telecom-available-start-time'
      #},
      {
        name: 'Type',
        value: 'type'
      }
    ]
  end


  private
  # There a bunch of extensions.   We will start with the ones that are of direct interest and go from there.
  # addresses[0].extension[0].extension[0].valueDecimal
  def parse_address(organization)
    #start with the geolocation extension on address
    lat = 0;
    long = 0;
    @geolocation=[]
    organization.address.each do |address|
      extensions = address.extension
     if extensions.present?
          extensions.each do |extension|
              if extension.url.include?('geolocation')
                 extension.extension.each do |latlong|
                    if latlong.url.include?('latitude')
                       lat = latlong.valueDecimal
                    end
                    if latlong.url.include?('longitude')
                      long = latlong.valueDecimal
                    end
                end
                @geolocation << {latitude: lat, longitude: long }
            end
        end
    end
  end
end
end

app/controllers/organizations_controller.rb
# frozen_string_literal: true

################################################################################
#
# Organizations Controller
#
# Copyright (c) 2019 The MITRE Corporation.  All rights reserved.
#
################################################################################

require 'json'
require 'cgi'

class OrganizationsController < ApplicationController
  
  before_action :connect_to_server, only: [:index, :show]

  #-----------------------------------------------------------------------------

  # GET /organizations

  def index
    return unless @client

    typecodes = 'fac,bus,prvgrp,payer,atyprv'
    if params[:page].present?
      update_page(params[:page])
    else
      if params[:query_string].present?
        parameters = query_hash_from_string(params[:query_string])

        reply = @client.search(
          FHIR::Organization,
          search: {
            parameters: parameters.merge(
       #       _profile: 'http://hl7.org/fhir/us/davinci-pdex-plan-net/StructureDefinition/plannet-Organization'
               type:      typecodes         
            )
          }
        )
      else
        reply = @client.search(
          FHIR::Organization,
          search: {
            parameters: {
        #      _profile: 'http://hl7.org/fhir/us/davinci-pdex-plan-net/StructureDefinition/plannet-Organization'
              type:      typecodes    
            }
          }
        )
      end
    
      @bundle = reply.resource
      @search = "<Search String in Returned Bundle is empty>"
      #binding.pry 
      @search = CGI.unescape(@bundle.link.select { |l| l.relation === "self"}.first.url) if @bundle && @bundle.link && @bundle.link.first 
    end

    update_bundle_links

    @query_params = Organization.query_params
    @organizations = []
    @organizations = @bundle.entry.map(&:resource) if @bundle
  end

  #-----------------------------------------------------------------------------

  # GET /organizations/[id]

  def show
    return unless @client

    reply = @client.read(FHIR::Organization, params[:id])
    fhir_organization = reply.resource
    @organization = Organization.new(fhir_organization) unless fhir_organization.nil?
  end

end

app/helpers/organization_helper.rb
# frozen_string_literal: true

################################################################################
#
# Organization Helper
#
# Copyright (c) 2019 The MITRE Corporation.  All rights reserved.
#
################################################################################

module OrganizationHelper
end

app/views/organizations/index.html.erb
<section class='container'>
  <h3 class='page-title'>Organizations</h3>

  <% if @client %>
  <section class='row'>
    <div class='col-12'>
      <%= render 'partials/query' %>
      <%= render 'partials/pagination', resource: :organizations %>
    </div>
    <div class='col-12'>
      <div class="accordion mb-4" id="searchAccordion">
        <div class="accordion-item">
          <h2 class="accordion-header" id="headingOne">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
              Search
            </button>
          </h2>
          <div id="collapseOne" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#searchAccordion">
            <div class="accordion-body">
              <%= render 'partials/search_form',
                         query_params: @query_params,
                         search_path: organizations_path
              %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class='col-12'>
      <table class='table table-dark table-striped'>
        <thead>
          <tr>
            <th scope='col'>Name</th>
            <th scope='col'>Type</th>
            <th scope='col'>Phone/Fax</th>
            <th scope='col'>Locations</th>
            <th scope='col'>Contacts</th>
          </tr>
        </thead>
        <tbody>
          <% @organizations.each do |fhir_organization| %>
            <% organization = Organization.new(fhir_organization) %>
            <tr>
              <td><%= link_to sanitize(organization.name), organization_path(organization.id) %></td>
              <td><%= organization.type.map(&:text).join(',') %></td>
              <td>
                <% organization.telecoms.each do |telecom| %>
                  <%= display_telecom(telecom) %><br />
                <% end %>
              </td>
              <td>
                <% organization.addresses.each do |address| %>
                  <% address.line.each do |line| %>
                    <%= sanitize(line) %><br />
                  <% end %>
                  <%= sanitize(address.city) %>, 
                  <%= sanitize(address.state) %> 
                  <%= display_postal_code(address.postalCode) %><br />
                  <br />
                <% end %>
              </td>
              <td>
                <% organization.contacts.each do |contact| %>
                  <%= display_human_name(contact.name) %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class='col-12'>
      <%= render 'partials/pagination', resource: :organizations, header: false %>
    </div>
  </section>
</section>

  <% else %>
    <%= render 'partials/server_connect' %>
  <% end %>

app/views/organizations/show.html.erb
<section class='container'>
  <% if @client %>
  <section class='row'>
    <% unless @organization.nil? %>
      <div class='col-12'>
        <h2>Organization: <%= sanitize(@organization.name) %></h2>
      </div>
      
      <div class='col-6' id='map'>
       <%= render partial: 'partials/mapleaflet', locals: { lat: @organization.geolocation[0][:latitude] , long: @organization.geolocation[0][:longitude] }  if @organization.geolocation[0] %>
      </div>
      <div class='col-6'>
        <table class='table table-dark'>
          <tr>
            <td>Phone/Fax:</td>
            <td>
              <% @organization.telecoms.each do |telecom| %>
                <%= display_telecom(telecom) %><br />
              <% end %>
            </td>
          </tr>
          <tr>
            <td>Type:</td>
            <td>
              <%= @organization.type.map(&:text).join(',') %>
            </td>
          </tr>
          <tr>
          <tr>
            <td>Locations:</td>
            <td>
              <% @organization.addresses.each do |address| %>
                <% address.line.each do |line| %>
                  <%= sanitize(line) %><br />
                <% end %>
                <% if address.city || address.state || (address.postalCode && address.postalCode != "00000") %>
                <%= sanitize(address.city) %>, 
                <%= sanitize(address.state) %> 
                <%= display_postal_code(address.postalCode) %><br />
                <% end %>
                <br />
              <% end %>
            </td>
          </tr>
          <tr>
            <td>GeoLocations:</td>
            <td>
              <% @organization.geolocation.each do |geoloc| %>
               ( <%= geoloc[:longitude].to_s %> , <%= geoloc[:latitude].to_s %> )
               <br />
              <% end %>
            </td>
          </tr>

          <tr>
            <td>Contact:</td>
            <td>
              <% @organization.contacts.each do |contact| %>
                <%= display_human_name(contact.name) %><br />
              <% end %>
            </td>
          </tr>
          <% @organization.extensions.each do |extension| %>
          <tr>
            <td><%= extension_title(extension.url) %>:</td>
            <td>
              <% if extension.extension.present? %>
              <!-- only going one level deep on extensions -->
                <% extension.extension.each do |child_extension| %>
                  <%= extension_title(child_extension.url) %>: <i><%= display_leaf_extension(child_extension) %></i>
                  <br />
                <% end %>
              <% else %>
                <%= display_leaf_extension(extension) %>
              <% end %>
              <br />
            </td>
          <tr>
        <% end %>
        </table>
      </div>
    <% else %>
      Not available
    <% end %>

  </section>
</section>
  <% else %>
    <%= render 'partials/server_connect' %>
  <% end %>